"""Dump the dashboard YAML into cards.js so the preview renders the real tree.

The preview must not keep a hand-written copy of the cards: that copy drifts.
This script parses alarm-dashboard.yaml and writes the view configuration as
JSON, so whatever the preview draws is what Home Assistant would get.

    python dashboards/preview/build_cards.py
"""

from __future__ import annotations

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
SOURCE = HERE.parent / "alarm-dashboard.yaml"
TARGET = HERE / "cards.js"


def main() -> int:
    try:
        import yaml
    except ImportError:
        raise SystemExit("pyyaml is required: python -m pip install pyyaml")

    view = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))

    # A view file pasted into the UI is exactly this mapping; in YAML mode it
    # is wrapped in `views:`. Strip that wrapper if it is there so the preview
    # works with either shape.
    if "views" in view:
        view = view["views"][0]

    body = json.dumps(view, ensure_ascii=False, indent=2)
    TARGET.write_text(
        "// Generated by build_cards.py from ../alarm-dashboard.yaml - do not edit.\n"
        f"window.ALARM_VIEW = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {TARGET} ({len(body)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
