// Generated by build_cards.py from ../alarm-dashboard.yaml - do not edit.
window.ALARM_VIEW = {
  "type": "sections",
  "max_columns": 3,
  "dense_section_placement": true,
  "title": "Alarmanlage",
  "subtitle": "Crow AAP IP Module · Bereich A",
  "path": "alarm",
  "icon": "mdi:shield-lock",
  "header": {
    "layout": "responsive",
    "badges_position": "bottom",
    "badges_wrap": "wrap"
  },
  "badges": [
    {
      "type": "entity",
      "entity": "alarm_control_panel.security_crow_alarm_system_a",
      "name": "Alarmanlage",
      "color": "state",
      "show_name": true,
      "show_state": true
    },
    {
      "type": "entity",
      "entity": "binary_sensor.alles_geschlossen",
      "name": "Haus gesichert",
      "icon": "mdi:shield-check",
      "color": "green",
      "show_name": true,
      "show_state": false,
      "visibility": [
        {
          "condition": "state",
          "entity": "binary_sensor.alles_geschlossen",
          "state": "on"
        }
      ]
    },
    {
      "type": "entity",
      "entity": "binary_sensor.alles_geschlossen",
      "name": "Zonen offen",
      "icon": "mdi:shield-alert",
      "color": "red",
      "show_name": true,
      "show_state": false,
      "visibility": [
        {
          "condition": "state",
          "entity": "binary_sensor.alles_geschlossen",
          "state": "off"
        }
      ]
    },
    {
      "type": "entity",
      "entity": "binary_sensor.crow_alarm_system_system_tamper",
      "name": "Sabotage",
      "icon": "mdi:alert-decagram",
      "color": "red",
      "show_name": true,
      "show_state": false,
      "visibility": [
        {
          "condition": "state",
          "entity": "binary_sensor.crow_alarm_system_system_tamper",
          "state": "on"
        }
      ]
    },
    {
      "type": "entity",
      "entity": "binary_sensor.crow_alarm_system_mains_power",
      "name": "Netzstrom",
      "icon": "mdi:power-plug-off",
      "color": "red",
      "show_name": true,
      "show_state": false,
      "visibility": [
        {
          "condition": "state",
          "entity": "binary_sensor.crow_alarm_system_mains_power",
          "state": "off"
        }
      ]
    },
    {
      "type": "entity",
      "entity": "input_boolean.expert_mode",
      "name": "Expert",
      "icon": "mdi:account-hard-hat",
      "color": "deep-purple",
      "show_name": true,
      "show_state": false,
      "tap_action": {
        "action": "toggle"
      },
      "visibility": [
        {
          "condition": "state",
          "entity": "input_boolean.expert_mode",
          "state": "off"
        }
      ]
    },
    {
      "type": "entity",
      "entity": "input_boolean.expert_mode",
      "name": "Standard",
      "icon": "mdi:eye-outline",
      "color": "blue",
      "show_name": true,
      "show_state": false,
      "tap_action": {
        "action": "toggle"
      },
      "visibility": [
        {
          "condition": "state",
          "entity": "input_boolean.expert_mode",
          "state": "on"
        }
      ]
    }
  ],
  "sections": [
    {
      "type": "grid",
      "column_span": 2,
      "cards": [
        {
          "type": "heading",
          "heading": "Haus Alarmsystem",
          "icon": "mdi:shield-home",
          "heading_style": "title",
          "badges": [
            {
              "type": "entity",
              "entity": "sensor.crow_system_status",
              "color": "state",
              "show_state": true
            },
            {
              "type": "entity",
              "entity": "binary_sensor.alles_geschlossen",
              "icon": "mdi:shield-check",
              "color": "green",
              "show_state": false,
              "visibility": [
                {
                  "condition": "state",
                  "entity": "binary_sensor.alles_geschlossen",
                  "state": "on"
                }
              ]
            }
          ]
        },
        {
          "type": "conditional",
          "conditions": [
            {
              "condition": "state",
              "entity": "alarm_control_panel.security_crow_alarm_system_a",
              "state": "triggered"
            }
          ],
          "card": {
            "type": "markdown",
            "content": "## Alarm ausgelöst\n{% set zone = state_attr('alarm_control_panel.security_crow_alarm_system_a', 'alarm_zone') %}\n{% if zone %}\nDer Melder hat **Zone {{ zone }}** gemeldet.\n{% else %}\nDie Anlage hat die auslösende Zone noch nicht übermittelt.\n{% endif %}\n\nErst die Ursache feststellen, dann quittieren - die Reihenfolge steht\nim Ereignisprotokoll (Expertenmodus).\n"
          }
        },
        {
          "type": "conditional",
          "conditions": [
            {
              "condition": "or",
              "conditions": [
                {
                  "condition": "state",
                  "entity": "binary_sensor.crow_alarm_system_mains_power",
                  "state": "off"
                },
                {
                  "condition": "state",
                  "entity": "binary_sensor.crow_alarm_system_system_battery",
                  "state": "on"
                },
                {
                  "condition": "state",
                  "entity": "binary_sensor.crow_alarm_system_zone_battery",
                  "state": "on"
                },
                {
                  "condition": "state",
                  "entity": "binary_sensor.crow_alarm_system_system_tamper",
                  "state": "on"
                },
                {
                  "condition": "state",
                  "entity": "binary_sensor.crow_alarm_system_phone_line",
                  "state": "off"
                },
                {
                  "condition": "state",
                  "entity": "binary_sensor.crow_alarm_system_dialler",
                  "state": "off"
                },
                {
                  "condition": "state",
                  "entity": "alarm_control_panel.security_crow_alarm_system_a",
                  "state": "unavailable"
                }
              ]
            }
          ],
          "card": {
            "type": "markdown",
            "content": "## Störung der Alarmanlage\nDie Anlage meldet:\n{% if is_state('binary_sensor.crow_alarm_system_mains_power', 'off') %}\n- **Netzstrom** ausgefallen\n{% endif %}\n{% if is_state('binary_sensor.crow_alarm_system_system_battery', 'on') %}\n- **Systembatterie** schwach\n{% endif %}\n{% if is_state('binary_sensor.crow_alarm_system_zone_battery', 'on') %}\n- **Zonenbatterie** schwach\n{% endif %}\n{% if is_state('binary_sensor.crow_alarm_system_system_tamper', 'on') %}\n- **Sabotagekontakt** ausgelöst\n{% endif %}\n{% if is_state('binary_sensor.crow_alarm_system_phone_line', 'off') %}\n- **Telefonleitung** gestört\n{% endif %}\n{% if is_state('binary_sensor.crow_alarm_system_dialler', 'off') %}\n- **Wählgerät** gestört\n{% endif %}\n{% if is_state('alarm_control_panel.security_crow_alarm_system_a', 'unavailable') %}\n- **keine Verbindung** zum IP-Modul\n{% endif %}\n\nDie Zonen sind weiterhin gesichert, aber die Anlage kann eine Meldung\nnicht sicher weiterleiten. Details unter *Systemstatus* (Expertenmodus).\n"
          }
        },
        {
          "type": "conditional",
          "conditions": [
            {
              "condition": "state",
              "entity": "alarm_control_panel.security_crow_alarm_system_a",
              "state": "arming"
            }
          ],
          "card": {
            "type": "markdown",
            "content": "## Ausgangsverzögerung läuft\nDie Anlage wird scharf geschaltet. Türen schließen und das Haus verlassen.\n"
          }
        },
        {
          "type": "grid",
          "columns": 2,
          "square": false,
          "cards": [
            {
              "type": "tile",
              "entity": "alarm_control_panel.security_crow_alarm_system_a",
              "name": "Haus Alarmsystem",
              "icon": "mdi:shield-home",
              "state_content": [
                "state",
                "last_changed"
              ],
              "features": [
                {
                  "type": "alarm-modes"
                }
              ]
            },
            {
              "type": "markdown",
              "content": "{% set zonen = expand(\n     'binary_sensor.crow_alarm_doors_eingangstur',\n     'binary_sensor.crow_alarm_doors_terrassentur',\n     'binary_sensor.crow_alarm_windows_wohnzimmer_fenster',\n     'binary_sensor.crow_alarm_system_kuche_fenster',\n     'binary_sensor.crow_alarm_windows_gastewc_fenster',\n     'binary_sensor.crow_alarm_windows_schlaf_bad_fenster',\n     'binary_sensor.crow_alarm_windows_kinder_fenster'\n   ) | selectattr('state', 'eq', 'on') | list %}\n{% if zonen %}\n## {{ zonen | length }} von 7 Zonen offen\n{{ zonen | map(attribute='name') | join(' · ') }}\n\nTüren und Fenster sind erst gesichert, wenn sie geschlossen sind.\n{% else %}\n## Alle Zonen geschlossen\nTüren und Fenster sind gesichert und die Anlage kann scharf\ngeschaltet werden.\n{% endif %}\n"
            }
          ]
        }
      ]
    },
    {
      "type": "grid",
      "cards": [
        {
          "type": "heading",
          "heading": "Zugang & Türen",
          "icon": "mdi:door-open",
          "heading_style": "subtitle"
        },
        {
          "type": "grid",
          "columns": 2,
          "square": false,
          "cards": [
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_doors_eingangstur",
              "name": "Eingangstür",
              "icon": "mdi:door",
              "color": "red",
              "state_content": [
                "state",
                "last_changed"
              ]
            },
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_doors_terrassentur",
              "name": "Terrassentür",
              "icon": "mdi:door-sliding",
              "color": "red",
              "state_content": [
                "state",
                "last_changed"
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "grid",
      "cards": [
        {
          "type": "heading",
          "heading": "Fenster (Perimeter)",
          "icon": "mdi:window-closed-variant",
          "heading_style": "subtitle"
        },
        {
          "type": "grid",
          "columns": 2,
          "square": false,
          "cards": [
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_windows_wohnzimmer_fenster",
              "name": "Wohnzimmer",
              "icon": "mdi:window-closed",
              "color": "red",
              "state_content": [
                "state",
                "last_changed"
              ]
            },
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_system_kuche_fenster",
              "name": "Küche",
              "icon": "mdi:window-closed",
              "color": "red",
              "state_content": [
                "state",
                "last_changed"
              ]
            },
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_windows_gastewc_fenster",
              "name": "Gäste-WC",
              "icon": "mdi:window-closed",
              "color": "red",
              "state_content": [
                "state",
                "last_changed"
              ]
            },
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_windows_schlaf_bad_fenster",
              "name": "Schlaf/Bad OG",
              "icon": "mdi:window-closed",
              "color": "red",
              "state_content": [
                "state",
                "last_changed"
              ]
            },
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_windows_kinder_fenster",
              "name": "Kinder OG",
              "icon": "mdi:window-closed",
              "color": "red",
              "state_content": [
                "state",
                "last_changed"
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "grid",
      "column_span": 2,
      "cards": [
        {
          "type": "heading",
          "heading": "Bewegung innen",
          "icon": "mdi:motion-sensor",
          "heading_style": "subtitle"
        },
        {
          "type": "grid",
          "columns": 2,
          "square": false,
          "cards": [
            {
              "type": "tile",
              "entity": "binary_sensor.bewegungsmelder_vorzimmer",
              "name": "Vorzimmer",
              "color": "amber",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.bewegungsmelder_keller_1",
              "name": "Keller 1",
              "color": "amber",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.bewegungsmelder_keller_2",
              "name": "Keller 2",
              "color": "amber",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.bewegungsmelder_gastewc",
              "name": "Gäste-WC",
              "color": "amber",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.bewegungsmelder_wc",
              "name": "WC",
              "color": "amber",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.bewegungsmelder_technikraum",
              "name": "Technikraum",
              "color": "amber",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.bewegungsmelder_wascheabwurfraum",
              "name": "Wäscheabwurf",
              "color": "amber",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.bewegungsmelder_lagerraum",
              "name": "Lagerraum",
              "color": "amber",
              "state_content": "state"
            }
          ]
        }
      ]
    },
    {
      "type": "grid",
      "column_span": 2,
      "visibility": [
        {
          "condition": "state",
          "entity": "input_boolean.expert_mode",
          "state": "on"
        }
      ],
      "cards": [
        {
          "type": "heading",
          "heading": "Systemstatus",
          "icon": "mdi:chip",
          "heading_style": "subtitle",
          "badges": [
            {
              "type": "entity",
              "entity": "sensor.crow_system_status",
              "color": "state",
              "show_state": true
            }
          ]
        },
        {
          "type": "grid",
          "columns": 3,
          "square": false,
          "cards": [
            {
              "type": "tile",
              "entity": "sensor.crow_system_status",
              "name": "Panelstatus",
              "icon": "mdi:shield-home",
              "color": "state",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_system_mains_power",
              "name": "Netzstrom",
              "icon": "mdi:power-plug",
              "color": "green",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_system_system_battery",
              "name": "Systembatterie",
              "icon": "mdi:battery-alert-variant-outline",
              "color": "red",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_system_zone_battery",
              "name": "Zonenbatterie",
              "icon": "mdi:battery-check-outline",
              "color": "red",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_system_system_tamper",
              "name": "Sabotage",
              "icon": "mdi:alert-decagram",
              "color": "red",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_system_phone_line",
              "name": "Telefonleitung",
              "icon": "mdi:phone",
              "color": "red",
              "state_content": "state"
            },
            {
              "type": "tile",
              "entity": "binary_sensor.crow_alarm_system_dialler",
              "name": "Wählgerät",
              "icon": "mdi:phone-outgoing",
              "color": "red",
              "state_content": "state"
            }
          ]
        }
      ]
    },
    {
      "type": "grid",
      "visibility": [
        {
          "condition": "state",
          "entity": "input_boolean.expert_mode",
          "state": "on"
        }
      ],
      "cards": [
        {
          "type": "heading",
          "heading": "Klassische Bedienung",
          "icon": "mdi:dialpad",
          "heading_style": "subtitle",
          "badges": [
            {
              "type": "button",
              "icon": "mdi:alarm-light",
              "text": "Panik",
              "color": "red",
              "tap_action": {
                "action": "perform-action",
                "perform_action": "alarm_control_panel.alarm_trigger",
                "target": {
                  "entity_id": "alarm_control_panel.security_crow_alarm_system_a"
                },
                "confirmation": {
                  "text": "Panikalarm wirklich auslösen?"
                }
              }
            }
          ]
        },
        {
          "type": "alarm-panel",
          "entity": "alarm_control_panel.security_crow_alarm_system_a",
          "name": "Haus Alarmsystem"
        }
      ]
    },
    {
      "type": "grid",
      "column_span": 3,
      "visibility": [
        {
          "condition": "state",
          "entity": "input_boolean.expert_mode",
          "state": "on"
        }
      ],
      "cards": [
        {
          "type": "heading",
          "heading": "Ereignisprotokoll",
          "icon": "mdi:history",
          "heading_style": "subtitle"
        },
        {
          "type": "logbook",
          "title": "Letzte 72 Stunden",
          "hours_to_show": 72,
          "target": {
            "entity_id": [
              "alarm_control_panel.security_crow_alarm_system_a",
              "binary_sensor.crow_alarm_doors_eingangstur",
              "binary_sensor.crow_alarm_doors_terrassentur",
              "binary_sensor.crow_alarm_windows_wohnzimmer_fenster",
              "binary_sensor.crow_alarm_system_kuche_fenster",
              "binary_sensor.crow_alarm_windows_gastewc_fenster",
              "binary_sensor.crow_alarm_windows_schlaf_bad_fenster",
              "binary_sensor.crow_alarm_windows_kinder_fenster",
              "binary_sensor.crow_alarm_system_system_tamper"
            ]
          }
        }
      ]
    },
    {
      "type": "grid",
      "column_span": 3,
      "visibility": [
        {
          "condition": "state",
          "entity": "input_boolean.expert_mode",
          "state": "on"
        }
      ],
      "cards": [
        {
          "type": "heading",
          "heading": "Zonenverlauf",
          "icon": "mdi:chart-timeline-variant",
          "heading_style": "subtitle"
        },
        {
          "type": "history-graph",
          "title": "Letzte 24 Stunden",
          "hours_to_show": 24,
          "entities": [
            {
              "entity": "alarm_control_panel.security_crow_alarm_system_a",
              "name": "Alarmanlage"
            },
            {
              "entity": "binary_sensor.crow_alarm_doors_eingangstur",
              "name": "Eingangstür"
            },
            {
              "entity": "binary_sensor.crow_alarm_doors_terrassentur",
              "name": "Terrassentür"
            },
            {
              "entity": "binary_sensor.crow_alarm_windows_wohnzimmer_fenster",
              "name": "Wohnzimmer"
            },
            {
              "entity": "binary_sensor.crow_alarm_system_kuche_fenster",
              "name": "Küche"
            },
            {
              "entity": "binary_sensor.crow_alarm_windows_gastewc_fenster",
              "name": "Gäste-WC"
            },
            {
              "entity": "binary_sensor.crow_alarm_windows_schlaf_bad_fenster",
              "name": "Schlaf/Bad OG"
            },
            {
              "entity": "binary_sensor.crow_alarm_windows_kinder_fenster",
              "name": "Kinder OG"
            }
          ]
        }
      ]
    }
  ]
};
