"""Download the Material Design Icons used by the preview and write icons.js.

The preview has to work offline, so the icon paths are vendored next to it
instead of being pulled from a CDN at runtime.

    python dashboards/preview/fetch_icons.py
"""

from __future__ import annotations

import json
import pathlib
import re
import urllib.request

VERSION = "7.4.47"
BASE = f"https://cdn.jsdelivr.net/npm/@mdi/svg@{VERSION}/svg"

# Every icon referenced by alarm-dashboard.yaml, plus the ones the preview's
# own chrome draws (alarm-panel buttons, relative time, ...).
ICONS = [
    # dashboard
    "account-hard-hat",
    "alarm-light",
    "alert-decagram",
    "battery-alert-variant-outline",
    "battery-check-outline",
    "chart-timeline-variant",
    "chip",
    "door",
    "door-open",
    "door-sliding",
    "eye-outline",
    "history",
    "dialpad",
    "motion-sensor",
    "phone",
    "phone-outgoing",
    "power-plug",
    "power-plug-off",
    "shield-alert",
    "shield-check",
    "shield-home",
    "shield-lock",
    "window-closed",
    "window-closed-variant",
    # preview chrome / alarm panel card
    "airplane",
    "alert-circle-outline",
    "alert-outline",
    "bell-ring",
    "check",
    "clock-outline",
    "cog",
    "home",
    "information-outline",
    "lock",
    "minus",
    "moon-waning-crescent",
    "plus",
    "shield",
    "shield-off",
]

PATH_RE = re.compile(r'<path d="([^"]+)"')


def main() -> int:
    out = pathlib.Path(__file__).resolve().parent / "icons.js"
    paths: dict[str, str] = {}
    for name in ICONS:
        with urllib.request.urlopen(f"{BASE}/{name}.svg", timeout=30) as response:
            body = response.read().decode("utf-8")
        found = PATH_RE.findall(body)
        if not found:
            raise SystemExit(f"no <path> in {name}.svg")
        paths[name] = " ".join(found)

    lines = [
        "// Generated by fetch_icons.py - do not edit.",
        f"// Material Design Icons {VERSION} (@mdi/svg), MIT licence.",
        "window.MDI = {",
    ]
    for name, data in sorted(paths.items()):
        lines.append(f"  {json.dumps(name)}: {json.dumps(data)},")
    lines.append("};")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(paths)} icons)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
